{% set name = "jupyterlab_pygments" %}
{% set version = "0.2.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 2d48bcdd666043afc086af56adaf6bb79bbeffb1d73ed00ec4a2113f6cc22581

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . --no-deps --ignore-installed --no-cache-dir -vvv

requirements:
  host:
    - python
    - pip
  run:
    - python
    - pygments >=2.4.1,<3

test:
  imports:
    - jupyterlab_pygments

about:
  home: http://github.com/JupyterLab/jupyterlab_pygments
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE
  summary: Pygments syntax coloring scheme making use of the JupyterLab CSS variables
  description: |
    The goal is to enable the use of JupyterLab's themes with pygments-generated HTML.
  dev_url: https://github.com/JupyterLab/jupyterlab_pygments

extra:
  recipe-maintainers:
    - SylvainCorlay
    - maartenbreddels
